<?php
$block = $this;
$interest = $block->getInterest();
?>
<div class="fieldset">
    <?php foreach($interest as $i): ?>
        <ul class="form-list">
            <li class="field no-label">
            <label class="label" for="<?php echo $this->escapeQuote($i['interest']['id']) ?>">
                <h4><?php echo $this->escapeQuote($i['interest']['title']) ?></h4>
            </label>
            </li>
            <?php echo $this->getLayout()->createBlock(
                'squalomail/group_type',
                'squalomail.group.type',
                array('interests' => $i)
            )->toHtml(); ?>
        </ul>
    <?php endforeach; ?>
</div>
