<?php
$force = $this->isForceEnabled();
$check = $this->isChecked();
$hidden = $this->isForceHidden();
$addToPostOnLoad = $this->addToPostOnLoad();
$generalList = $this->getGeneralList();
?>
<script type="text/javascript">
    addSubscribeToPost = function (element) {

        //save old clicked lists and then removes element
        var subscribeValue = '';
        var checkedLists = '';
        <?php if (!$force) : ?>
        if ($('squalomail-subscribe')) {
            checkedLists = $('squalomail-subscribe').getValue();
            subscribeValue = checkedLists + ',';
            $('squalomail-subscribe').remove();
        }
        <?php endif; ?>

        var hidden = false;
        <?php if ($hidden) : ?>
        hidden = true;
        <?php endif; ?>
        //if checked add this element else remove it
        if (element.checked || hidden) {
            var inputer = new Element('input', {
                name: "squalomail_subscribe",
                id: "squalomail-subscribe",
                value: subscribeValue + element.readAttribute('value'),
                type: "hidden"
            });
            try {
                Element.insert(Form.findFirstElement(payment.form), inputer);

            } catch (notelem) {
                $("co-payment-form").insert(inputer);
            }
        } else {
            var arrCheckedLists = checkedLists.split(',');
            var pos = arrCheckedLists.indexOf(element.readAttribute('value'));
            if (pos != -1) {
                arrCheckedLists.splice(pos, 1);
                checkedLists = arrCheckedLists.join(',');
                var inputer = new Element('input', {
                    name: "squalomail_subscribe",
                    id: "squalomail-subscribe",
                    value: checkedLists,
                    type: "hidden"
                });
                if (inputer.value) {
                    try {
                        Element.insert(Form.findFirstElement(payment.form), inputer);
                    } catch (notelem) {
                        $("co-payment-form").insert(inputer);
                    }
                }
            }
        }

    };
</script>

<div class="buttons-set"<?php if ($hidden) : ?> style="display:none;"<?php
endif; ?>>
    <!-- General Subscription -->
    <div class="page-title">
        <h1><?php echo $this->escapeQuote($this->__('Newsletter Subscription')); ?></h1>
    </div>
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="squalomail-multisubscribe">
        <ul class="squalomail-general-list">
            <li class="listdata"><input<?php if ($check): ?> checked="checked"<?php
           endif; ?> type="checkbox"
                     onchange="addSubscribeToPost(this);"
                     name="list[<?php echo $this->escapeHtml($generalList); ?>][subscribed]"
                     id="squalomail-trigger"
                     value="<?php echo $this->escapeHtml($generalList); ?>"
                     title="<?php echo $this->escapeHtml($generalList); ?>"
                     class="squalomail-list-subscriber"/>
                <label for="squalomail-trigger">
                    <?php echo $this->escapeQuote($this->__('General Subscription')); ?>
                </label>
            </li>
        </ul>
    </div>
    <!-- General Subscription -->
</div>

<script type="text/javascript">
    //If force subscription or checked by default set the elements as clicked
    <?php if ($addToPostOnLoad):?>addSubscribeToPost($('squalomail-trigger'));
    <?php endif; ?>
</script>
